### ISSUE TITLE
only black screen visible with controllers

### ISSUE THREAD

**Issue by ishangupta-1510** [AgoraIO-Community/ReactNative-UIKit-example#2]
import React, {useState} from 'react';
import AgoraUIKit from 'agora-rn-uikit';

const App = () => {
  const [videoCall, setVideoCall] = useState(true);
  const rtcProps = {
    appId: '240bd9ad79ff48e69d0035d81704d7f0',
    channel: 'test',
  };
  const callbacks = {
    EndCall: () => setVideoCall(false),
  };
  return videoCall ? (
    <AgoraUIKit rtcProps={rtcProps} callbacks={callbacks} />
  ) : (
    <></>
  );
};

export default App;

**Comment by NikkiChristofi** [comment]
@ishangupta-1510 we had the same problem and were able to solve it by adding a token to the rtcProps, so:

`const rtcProps = {
appId: 'your app id',
channel: 'test',
token: 'your token here'
};`

To generate the token, go to your project in the Agora console, click on "config" and there'll be an option to generate a temp RTC token:

<img width="383" alt="Screenshot 2022-06-06 at 17 05 44" src="https://user-images.githubusercontent.com/44207183/172199777-c8e2dfd8-b5e1-4c47-a8dc-94b943448809.png">

Copy the token and add it to rtcProps and you should see the camera show.

**Comment by prakharjcis** [comment]
I have added appId,channel & token....
but still facing the same issue (BlackScreen)

**Comment by digitallysavvy** [comment]
Agora UIKits have been deprecated and the team recommends migrating to the Agora Video SDK
