### ISSUE TITLE
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 

### ISSUE THREAD

**Issue by Mihai-github** [AgoraIO-Community/ReactNative-UIKit-example#3]
Hi, I'm following the code example and getting this error when rendering the `AgoraUIKit` from `agora-rn-uikit`.

### error
Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

### code snippet

`import AgoraUIKit from 'agora-rn-uikit';`
`import { Text } from 'react-native';`
`import React, {useState} from 'react';`

`const [videoCall, setVideoCall] = useState(true);
    const connectionData = {
        appId: 'appId',
        channel: 'channel',
        token: 'token',
};`

`const callbacks = {
        EndCall: () => setVideoCall(false)
};`

`return (
   {videoCall ? (
      <AgoraUIKit
             connectionData={connectionData}
             rtcCallbacks={callbacks}
       />
       ) : (
       <Text onPress={() => setVideoCall(true)}>
          Start Call
        </Text>)}
)`

### package.json
`
dependencies {
  "react-native-agora": "^4.0.0",
   "agora-rn-uikit": "^4.0.2",
   "agora-react-native-rtm": "^1.5.0",
   "react": "17.0.2", 
   "react-native": "^0.64.1",
}
`

**Comment by EkaanshArora** [comment]
We’re in the process of updating the UIKit to work with 4.x version of the SDK. In the meantime you can downgrade react-native-agora to v3.7.x

**Comment by Mihai-github** [comment]
Hi @EkaanshArora, at the moment I tried the version:

`
"agora-rn-uikit": "^3.3.0",
"react-native-agora": "^3.5.3"
`

and seems to work fine, if you say then I can upgrade to v3.7.x to see if everything works.

Thanks!

**Comment by digitallysavvy** [comment]
Agora UIKits have been deprecated and the team recommends migrating to the Agora Video SDK
